# -*- coding: utf-8 -*-
"""PrakFiskom3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EaDHDplpO8kFubvohI3Z1x52ZMn7ecCy
"""



"""Fatasya Aulia Djihan 1217030013"""

# -*- coding: utf-8 -*-
"""Selamat Datang di Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EaDHDplpO8kFubvohI3Z1x52ZMn7ecCy?hl=id#scrollTo=fhC0VTGA6GDo

FATASYA AULIA DJIHAN-1217030013- TUGAS 3

Program dan hasil tugas 3 kolom 1
"""

import pandas as pd

last_names = ['Connor', 'Connor', 'Reese']
first_names = ['Sarah', 'John', 'Kyle']
df = pd.DataFrame({
  'first_name': first_names,
  'last_name': last_names,
})

url = "https://raw.githubusercontent.com/FillahAlamsyah/Machine-Learning-Prediksi-Posisi-Pada-Gerak-Parabola/main/DatabaseGerakParabola.txt"
database = pd.read_csv (url, sep=',')
'''pd.read_csv('data.csv')'''
print(database.columns)
print(database.describe())
print(database.head())
print(database.tail())

"""program dan hasil tugas 3 kolom 2 "sudah divariasikan"
"""

import numpy as np
x = [i for i in range(2,8)]
y1 = np.sin(x)
y2 = np.sin(x)
y3 = np.cos(x)

print(x,y1,y2,y3)

"""program dan hasil tugas 3 kolom 3 "sudah divariasikan"
"""

dataframe = pd.DataFrame({
    'x': x,
    'y1': y1,
    'y2': y2,
    'y3': y3
                             })
dataframe['z1'] = np.sin(x)
dataframe['z2'] = np.sin(x)
dataframe['z3'] = np.cos(x)


dataframe